keys:
  - &wsl age1w7dn54d69sqtxqgcxl2yu2u6hmvdxhfa9pltjz58kunalfef8s8s9qd4sl
creation_rules:
  - path_regex: (home|hosts|modules|secrets)/([^/]*/)?[a-zA-Z0-9]+[a-zA-Z0-9._-]*[a-zA-Z0-9]+.(yaml|yml)$
    key_groups:
      - age:
          - *wsl
