chezmoi_token: ENC[AES256_GCM,data:ClNzlWmEIvcUKgTGUaXUBMPyOnTE3esXjw/33BCPxCRPB31L7xsAeXuGkiiGYlc3IGvr2Jd8BStt2LpckGWbUlQO6eSb98jVvUKl+VRWu4FXDTRe5xc7x5XstzOxSA==,iv:v4Wmse9iAkyoyB3ohQCAXY1kUX/fsiNqVS/yvvAjEdA=,tag:gRShwOxLdhA+lGX77ZpoOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v0ql4zy5fvk6wjzw48j5g8dl7hfv79mjwdhdcg2rpw4rr02009eqslekdx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTY0dFcXI0OXY4a05IaGlD
            Z29IZEtkTGNOYkFxVXVqc2NMcVVTSWp3a200CiswbkN6L0NXODZPNzMvbHUwK1NF
            cUlZNmMvYzdrdFArdlk0TUVXbGlrOTQKLS0tIDhSNzF5Rmd2aEhiNTB6d2FpdjF2
            eTJlSUJpcDg4Mk5LWE5pdE9FMkxpQ1EK4pM9D/Fy3kqYwMBqGN2r0UxvlTsMKFPA
            1Hu0OYeFi6R+YgEAUvRvK1qqJPQW9IRO1zqHOHcs8xECnG6XnaOycA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-07T21:26:56Z"
    mac: ENC[AES256_GCM,data:+EcUyMSn3j+IPfa6/MhYZCCP483hd9NMHDwztB83x9ZmmshUZZO57zysFtTaCozYbgqP8ySgt5c0F7pYdhFkZhVYuloYsejWHxpMM9zrUgyTvv9oXXt4dj27RvF3LV5x/ap7LSeQPt6eMJZb4pOBErXS6jfgdZ8I7gmSLpvsg/Y=,iv:QottXgoRTfTVgRdVAHVu6hgzclYfqX0c1uJLYbvlnHk=,tag:pAyyrij4fopz10chQ4QHpQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
