chezmoi_token: ENC[AES256_GCM,data:qFJzJ9bpKP9gYhmJqdIiXs6G/EQSlPiktMMKX0UAfziFCU8QPewrklndp8Q+Q6a7XHy+mVPB4EHoOYJui9MID/2VjLDUUg95rQhbn01PgAEwW9tWuvKIoZmL1o0AMQ==,iv:KBQVdOSuocpGYsv4DzI7Q0EZwV6/LPK0fUdP2bQu+Eo=,tag:FB6Cqkoc3QxIs1QVjyjaBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1543eqd35ny388nmjqz88uzdrlvntjvclcm2zd90wswtq88yad4dq0dl5vx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RFlPekpDbHh0M1U5Um82
            d0ZtdEdPT3hSNDI5RHM5YndwdkJSU29rZ0NNCnZsZnpEcUZjdnNwNjVRSkpWTkU1
            L0R0VDg4d0ROM1hVRWJITGROTGpndXcKLS0tIG9WYnVzb2NOWHl2UzNobFNmTjVy
            S1VXd2x5MzREcDR3eWlrdHh1L2FyZUEKgc9859tbTk9Uv3UjEUFA/TDE0awqxC4T
            bxy/eE7CroB10waUSl+xKo3pxhWRx3vIXqHiFbBIFz63DZLfbSNU5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-06T14:34:17Z"
    mac: ENC[AES256_GCM,data:gYMG61IR6m/criQYPjMhz1z4pnIuI+t0K3NUb1XmtNqM0tPKuPmxo4FxSZTMOzLc57UoBfnXHhF6zuOboFVjqZqwSix/eIRgWsf40SUQaMpq/BQ4/UrC4YcdUjPHtae6PiWPnDav2e0EX51LTTNuIpgtmGjFLUBuczvgvNy15y0=,iv:Y9IOFSIXDcCa2G7GnUqi87ZpkmB1XzSTD20guAXC71I=,tag:sjUT3cxUKFKASpxhNGkNBA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
