data:
    access_token: ENC[AES256_GCM,data:sgzoO7GMfgRccHa3C1cjjRG0gwH0SxBzhrB82j3h47vuW10YEnW1x8+8VzMSSP8gpMjXFUC3Br7Sv7K61WH4ibZEMnUNfbiTBAjWKU82/QNt3/e7nOplj0fhLiNV3Q==,iv:j4AdqqdHON83OOHbgp410JBWoL/1zOevEKvPxc7eTL4=,tag:Y7azUoXtQRV93/axjTUzNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v0ql4zy5fvk6wjzw48j5g8dl7hfv79mjwdhdcg2rpw4rr02009eqslekdx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYlpYUG5ZR0hHMkdFdGE1
            WHplVHM5RmY2WWZDSFEyWnN5d0ZNUTZDVFZNCmhVenpYM3dmTUlySzBSV096Nkxj
            MGJueVB5RUdkRmJOcGlKbHZsRm5KOEkKLS0tIEhOeDBZL0VxU21NeWU3UHlnVlY2
            N3hoT0tWS08wK3BidFJvUWVFSUF5TjAKL8fWrs3b+q7W/iRbDZ1R3DW+EsIHhzA2
            c0QiDe5iyj79u/yaBV1obCzb1A3aI3XkFNfvgUy7Aoci9g4ifOqfsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-07T20:43:36Z"
    mac: ENC[AES256_GCM,data:A2ujsy3g8aK7hGi4hAMzb8I1Z9ebKsc6PeKHXoVcimAceTVL8XIylSIBPmCglpLMBntOxgjYnOJpFIproRl0aCFoVbDqhsLOxR7+Owk82CwfQKjrjLVEDiDlZfe6K9w2hIFdP0XB1z4myBgwUXLnj12004OqXJWnMa9MsgFyMAY=,iv:KLwyIoj1/aytYgLqEXg3VkSWoV1i6OdtktTwROn4wCg=,tag:BfjfbmNSUIskzmfAkhPZEw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
