chezmoi_token: ENC[AES256_GCM,data:1J7p5vJoMtSVXTwu0RDiqC9q6ZAxSX7khHKRZi4/PKdOvtqYEl2oeeSz7/jcIba1aKjXN6CyqsyAUT9qkiZRxgJNGCPEvJ4H/fLvax/6owUCAUgqWg5mY/qQiumqrQ==,iv:bWAk+v4Sp0h41J3kHOF8oe54HyOjpoADnm3aRjYn8XA=,tag:3g+y5wRiC28NyjEG9jnMYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hk34w5q89zs3wka0ryswc7jat07v9uesezlnvtlpz2rhnc4p5uwqayknra
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYXpLYXhBalVPVDVzTGNZ
            cVNudmIyYUZDTjhsYVdCcW9xUFBraDlyTWdrCjYvMG5SZ3dSSlNTRTV3N1dGUE1Z
            aW1qc0pQbVZsT2VWYXRYWWMvZGtQb2sKLS0tIEJzRFJNVzJDVCtZdU1sTDJTeWRX
            NHdNN2FXcDJ0YStReUVaRzVGYmRaOWcKyv3tsbYHPmTFP90lvV4Ag5eR2U0WBUZd
            oxIvj7rb4jWh2qeuisPTRdl2S5zr3kiBew/XsgM5vx+TnZeMAuSEpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-07T18:42:54Z"
    mac: ENC[AES256_GCM,data:pJilg5/S6mm/zw0xUlfW+L4w0/Dm3WEIRgknRINde18RKOttEdkQIqN3/VcmVuszlBVS1TCEFhQ1VzgOYut+YfEaoMmYmeYiDimz1QISE81ApPjn/EnsTvoP+f2DpGS8AVCQXS355AobLxvhf7uSYXcHd+UN6LdXhoy8T3RWzYs=,iv:2AYrwp88LTV37Jk8GLcQ8BD0XuC5TYO898sA/Oof+1o=,tag:/kmKLuO6Tg45tGd9p1kDaA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
