chezmoi_token: ENC[AES256_GCM,data:+Rc366FyrryUXkPrJVlvA8gkk15L8PCHgJ//qsvG2TuunYnUfOgMMzErfllSOa9yp57qVmd7jyFD3mSCs5AJj77frrLi6AOFffBEtvO/rm2nPhutz23TXXtqBsURfQ==,iv:GBmOJ/qua/N802HJXoawlHI/IKK2327zhQZE4LOImfw=,tag:kz1lxzcT0AeIWGVywop2XQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k9mlg0spegls4g6s27chgtalx8uphrgvff4378s0dtph7xw77vmsrpjwdx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVHpZcDlFeDFkL1hmdElV
            TEJ4NTl0SlFwNUdXVHFTcnN4UEVtVXlwRUVnCk5taG90WXFJNlZ2aDMrUitmNm84
            UDFnMURmUlpVdldxSUtLcytOekdjYWcKLS0tIFVmRzU3WG1ZWko0c1J1QWk5Wm5M
            dFRrRkJVOGlUQUxJaWhRTVhHcW4zUFkKBBQrtRrwb64uVmF7kMRiEfQoYNAsqXy3
            lNvULlyOzqTqOjRqOWXnhw2fVYwXc8VokuJmY1vM1rAG4GzFnl3egw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-08T18:36:43Z"
    mac: ENC[AES256_GCM,data:jfqPS9cgq8QTs1EGyTc/jWFgAyEafCEH7CjFKMUlrj5VedEugOc4wFvuLSeot1zelfsIUFST0PZ2RUEF/owhzwKm//7HZIaNIe0Laws8PYQSNaGsoVySgRda/Yk6SgwDguyk1HqvEUyNe703REUyJWM2FPGxOZVbx57tkVvW9q0=,iv:TfhquTIX7XDjVLYli0kfYzrTqj0qiDFgbAh8oVJmVq0=,tag:BjPX6qwEMQuBqDt23UceCA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
