chezmoi_token: ENC[AES256_GCM,data:Go8MXBDnUqb3ET6ZKAEWpzbOA+LWV/MYBmhMY3xWr4cSETHU8UeROozJH9nItJ+KEVvxNKsuaroVRjaLFJ+OHoqU1DRk/TQSC56oPEbFyYhrDK5VGrGFwkY73ti+yA==,iv:+GWU2+qzqv4LioGCIG0eRnZ6TOVS6pjPfQao9U6axpg=,tag:JgKk4LYDRIYRtWZ2PgMj9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w7dn54d69sqtxqgcxl2yu2u6hmvdxhfa9pltjz58kunalfef8s8s9qd4sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdG9NTktycXM1ZFBqczJJ
            R2lKN1ZMVkR1dk1jWTZCbGIvMHJFZUgzL0RrCnVGL2hESlBHQzRwSGJoVHlXWi9E
            b0dtNExGWU9Xb25UUEVENlkzS0tUa1EKLS0tIEx0VmlVdy8xeTBQK3ZaaDlidnla
            NnFIbnQ2bGdibnp5aFRyZHFKN1psbWMKdrXgE5F1nTMbk5sQVjOM26iBJLyFezNS
            Wlk+ayslGoMTSraED09A5B7dLf/eJxpSMcWUOyrwsRHAoigdJ/0uCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-07T17:05:18Z"
    mac: ENC[AES256_GCM,data:m0+IKQrgDjLbuhfbBGXiXUDRAetbbaVKHqhC0oaQ7XqR31HpThgF719xJMgWnWJCQrho+xTRXzJLrOtIVxAemMIO4Ao9uPiaSKpH9+WUVeb+3ePYmbYhVOrjyWeiDAV0tfBuxABHbeHHD8in91rd+r2DVBPeoZulxAPTqwpyBgk=,iv:niBISQ7b8SEDAo37aBEW67RRDjYhoh8FCbMwZ/OU1cY=,tag:bquFkts/FmMhkyvRFuhSug==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
